# Generated by Django 2.2 on 2020-01-31 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook_with_me_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chefs', to='cook_with_me_app.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='cook_with_me_app.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='courses', to='cook_with_me_app.User'),
        ),
    ]
