# Generated by Django 2.2 on 2020-01-31 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook_with_me_app', '0002_auto_20200130_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chefs', to='cook_with_me_app.Restaurant'),
        ),
        migrations.AlterField(
            model_name='course',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='cook_with_me_app.Restaurant'),
        ),
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(default=None, related_name='courses', to='cook_with_me_app.User'),
        ),
    ]
