# Generated by Django 2.2 on 2020-01-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_with_me_app', '0005_user_restaurant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=155),
        ),
    ]
