# Generated by Django 2.2 on 2020-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_with_me_app', '0006_auto_20200130_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(default=None, related_name='courses', to='cook_with_me_app.User'),
        ),
    ]
